include:
 - project: fsl/fsl-ci-rules
   file:    .gitlab-ci.yml


stages:
  - test
  - fsl-ci-pre
  - fsl-ci-build
  - fsl-ci-deploy


test:python3.6:
  stage: test
  image: python:3.6
  tags:
    - docker
  script:
    - pip install ruamel.yaml
    - python -m unittest discover fsl_sub.tests -p "test_*.py"


test:python3.7:
  stage: test
  image: python:3.7
  tags:
    - docker
  script:
    - pip install ruamel.yaml
    - python -m unittest discover fsl_sub.tests -p "test_*.py"


test:python3.8:
  stage: test
  image: python:3.8
  tags:
    - docker
  script:
    - pip install ruamel.yaml
    - python -m unittest discover fsl_sub.tests -p "test_*.py"
