image: ruby:2.7
pages:
  script:
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
  tags:
    - docker
  artifacts:
    paths:
      - public
kramdown:
  parse_block_html: true