#!/bin/sh

# SHCOPYRIGHT

#RCFILE=${FSLDIR}/etc/fslconf/fsl_sub.cfg
RCFILE=/usr/local/share/fsl_sub/cfg
. $RCFILE

wd=$1
jid=$2
name=$3
shift 2

echo $$ >> ${SPOOLDIR}/${jid}
echo $wd >> ${SPOOLDIR}/${jid}
echo $@ >> ${SPOOLDIR}/${jid}

cd $wd
$@ > $name.o${jid} 2>&1

mv $SPOOLDIR/$jid $SPOOLDIR/completed/$jid
