---
# Queue definitions (Partitions in SLURM)
queues:
  # Queue name
  gpu.q:
    # Maximum job rum time
    time: 18000
    # Maximum memory per job (GB)
    max_size: 250
    # Maximum memory per CPU core (GB)
    slot_size: 64
    # Maximum number of threads per job (e.g. number of CPU cores)
    max_slots: 20
    # Available coprocessors
    copros:
      # Coprocessor name (same as configuration above)
      cuda:
        # Number of devices available per job (e.g. number of devices on a single node)
        max_quantity: 4
        # List of available classes
        classes:
          - K
          - P
          - V
    # Available parallel environments
    paralle_envs:
      - openmp
    # Should jobs be split over multiple slots when requires more RAM than available
    # in a single slot
    map_ram: true
    # Priority of queue, higher numbers win
    priority: 1
    # Group of queue - use this to group together variations of a queue based on
    # hardware types, the priority is then used to decide which variant to use
    group: 0
  short:
    time: 1440
    max_size: 160
    slot_size: 4
    max_slots: 16
    map_ram: true
    priority: 1
    group: 1
  long:
    time: 10080
    max_size: 368
    slot_size: 16
    max_slots: 24
    map_ram: true
    priority: 1
    group: 2
    default: True
  verylong.q:
    time: 1000000
    max_size: 500
    slot_size: 12
    max_slots: 8
    map_ram: False
    priority: 1
    group: 3